import type { Metadata } from "next";
import "./globals.css";
import "../css/contact.css"
import "../css/contents.css"
import "../css/doubleLineBtn.css"
import "../css/header.css"
import "../css/main.css"
import "../css/company.css"
import "../css/topAbout.css"
import "../css/InstagramContents.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ja">
          <body className="antialiased">{children}</body>
    </html>
  );
}
